import About from "@/components/About";
import Apartment from "@/components/Apartment";
import Building from "@/components/Building";
import { WppButton } from "@/components/Elements";
import Gallery from "@/components/Gallery";
import Hero from "@/components/Landing";
import Presentation from "@/components/Presentation";
import Layout from "@/layout";
import Head from "next/head";
import { FaWhatsapp } from "react-icons/fa";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Layout>
      <Hero />
      <Apartment />
      <Building />
      <Gallery />
      <About />
      <Presentation />
      <WppButton href='https://api.whatsapp.com/send?phone=5586999811672&text=Ol%C3%A1!%20Conheci%20a%20RAD%20pelo%20site%20e%20gostaria%20de%20tirar%20algumas%20d%C3%BAvidas.' target='_blank' ><FaWhatsapp size={20} color='#F1F1F1' /> WhatsApp</WppButton>
    </Layout>
      
    </>
  );
}
